export const commonTableOptions = {
  border: true,
  index: true,
  editBtn: false, // 编辑
  editBtnIcon: " ", // 图标
  delBtn: false, // 删除
  delBtnIcon: " ",
  updateBtnIcon: " ",
  saveBtnIcon: " ",
  cancelBtnIcon: " ",
  addBtnIcon: " ",
  indexLabel: "序号",
  stripe: true,
  menuAlign: "center",
  searchMenuSpan: 24,
  align: "center",
  viewBtn: false,
  viewBtnIcon: " ",
  card: false,
  columnBtn: false,
  menuWidth: 220,
  dialogClickModal: false,
  indexWidth: 90,
  searchLabelWidth: 100,
  labelWidth: 100,
  searchIcon: true,
  refreshBtn: false,
  searchMenuPosition: "right",
  searchBtnText: "查 询",
  labelPosition: "left",
  gutter: 24,
  searchGutter: 24,
  searchIndex: 3,
  searchShowBtn: false,
  searchBtn: false,
  emptyBtn: false,
  selection: false, // 可多选
  addBtn: false,
  menu: true,
  header: false,
  searchEnter: true,
  filterBtnNew: true,
  dialogCustomClass: "crud-dialog",
  column: []
};
